[package]
name = "hash_checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.16.3"
sha2 = "0.9.8"
md5 = "0.7.0"
sha1 = "0.6.0"
